/* 独立交互原型：全部业务内容由合成数据构造，不连接正式接口。 */
(() => {
  const $ = (selector, root = document) => root.querySelector(selector);
  const esc = value => String(value ?? "").replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const paths = {
    plus:'M12 5v14M5 12h14',chat:'M20 11.5a7.5 7.5 0 0 1-7.5 7.5H5l-3 3V11.5A7.5 7.5 0 0 1 9.5 4h3A7.5 7.5 0 0 1 20 11.5Z',
    bookmark:'M6 3h12v18l-6-4-6 4V3Z',layers:'m12 3 9 5-9 5-9-5 9-5Zm-9 9 9 5 9-5M3 16l9 5 9-5',
    search:'M10.5 17a6.5 6.5 0 1 0 0-13 6.5 6.5 0 0 0 0 13Zm5-2L21 21',arrow:'M5 12h14m-5-5 5 5-5 5',
    chevron:'m9 5 7 7-7 7',down:'m6 9 6 6 6-6',menu:'M4 6h16M4 12h16M4 18h16',up:'M12 19V5m-6 6 6-6 6 6',
    spark:'m12 3 2.3 6.7L21 12l-6.7 2.3L12 21l-2.3-6.7L3 12l6.7-2.3L12 3Z',
    info:'M12 17v-5m0-4v.1M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20Z',check:'m5 12 4 4L19 6',
    copy:'M8 8h12v13H8V8ZM4 16H2V2h12v2',code:'m8 6-6 6 6 6m8-12 6 6-6 6m-3-15-2 18',
    download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',book:'M12 5v16M2 4h6a4 4 0 0 1 4 4 4 4 0 0 1 4-4h6v16h-6a4 4 0 0 0-4 1 4 4 0 0 0-4-1H2V4Z',
    edit:'m15 4 5 5m-15 6 12-12 4 4-12 12-6 2 2-6Z',close:'m6 6 12 12M18 6 6 18',
    table:'M3 3h18v18H3V3Zm0 6h18M9 9v12',document:'M14 2H4v20h16V8l-6-6Zm0 0v6h6M8 12h8M8 16h8',
    metric:'M4 20V10m8 10V4m8 16v-8',more:'M5 12h.01M12 12h.01M19 12h.01',
    clock:'M12 8v5l3 2M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20Z',
    memory:'M9 3H6a3 3 0 0 0-3 3v3M15 3h3a3 3 0 0 1 3 3v3M3 15v3a3 3 0 0 0 3 3h3M21 15v3a3 3 0 0 1-3 3h-3M8 8h8v8H8V8Z',
    globe:'M2 12h20M12 2c5 6 5 14 0 20-5-6-5-14 0-20Zm0 20a10 10 0 1 0 0-20 10 10 0 0 0 0 20Z',
    trash:'M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7m4-7v7',stop:'M6 6h12v12H6V6Z',
    settings:'M4 7h16M4 17h16M9 4v6m6 4v6',back:'M19 12H5m5-5-5 5 5 5',publish:'M12 16V3m-5 5 5-5 5 5M4 14v7h16v-7',
  };
  const icon = name => `<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name] || paths.document}"/></svg>`;
  const hydrateIcons = (root = document) => root.querySelectorAll('[data-icon]').forEach(node => node.innerHTML = icon(node.dataset.icon));
  const money = cents => (cents / 100).toLocaleString('zh-CN', {minimumFractionDigits:2,maximumFractionDigits:2});
  const rows = Array.from({length:31}, (_, index) => ({date:`2026-01-${String(index+1).padStart(2,'0')}`, cents:322810 + ((index * 18471) % 208683), orders:184 + ((index * 31) % 217)}));
  rows[30].cents += 12843650 - rows.reduce((sum,row) => sum+row.cents,0);
  const sql = `SELECT\n  payment_date AS 日期,\n  SUM(net_revenue_cents) / 100.0 AS 净收入_元,\n  COUNT(DISTINCT order_id) AS 支付订单数\nFROM mart.order_revenue\nWHERE payment_date >= '2026-01-01'\n  AND payment_date < '2026-02-01'\n  AND channel = 'app'\n  AND is_test_order = 0\nGROUP BY payment_date\nORDER BY payment_date;`;
  const field = (name, type, meaning) => ({name,type,meaning});
  const orderFields = [field('order_id','STRING','订单的唯一标识。同一订单可能包含多个商品行。'),field('line_id','STRING','订单内的商品行编号，与订单号共同确定一行。'),field('payment_date','DATE','订单首次成功付款的日期，用于收入月份归属。'),field('channel','STRING','订单来源渠道：App、小程序、网页或合作渠道。'),field('paid_amount_cents','BIGINT','该商品行实际支付的金额，单位为分。'),field('refunded_amount_cents','BIGINT','截至统计日成功退款的金额，归回原付款日。'),field('net_revenue_cents','BIGINT','实际支付金额减去成功退款金额，单位为分。'),field('is_test_order','BOOLEAN','是否为测试订单；经营分析应排除值为 1 的记录。'),field('customer_id','STRING','下单用户标识，用于去重和客户分析。'),field('product_id','STRING','商品标识，关联商品分类和定价信息。'),field('quantity','INTEGER','该商品行购买的数量。'),field('updated_at','TIMESTAMP','最近一次更新该条记录的时间。')];
  const objects = [
    {id:'orders',name:'订单收入明细',physical:'mart.order_revenue',kind:'table',description:'记录每笔订单商品行的支付与退款情况。一行对应一个订单商品行，金额已按商品行分摊，可直接汇总。适合分析净收入、支付订单数和渠道表现。',fields:orderFields},
    {id:'payments',name:'支付流水',physical:'raw.payment_events',kind:'table',description:'记录每一次支付事件，包括支付成功、失败和重试。统计现金流时按事件发生时间取数；统计订单数时需要按订单去重。',fields:[field('event_id','STRING','一次支付事件的唯一编号。'),field('order_id','STRING','关联的订单标识。'),field('event_at','TIMESTAMP','支付事件发生的时间。'),field('amount_cents','BIGINT','本次事件的支付金额，单位为分。'),field('status','STRING','支付状态：成功、失败或处理中。')]},
    {id:'refunds',name:'退款流水',physical:'raw.refund_events',kind:'table',description:'记录成功退款和退款处理中产生的事件。现金流口径按退款发生日统计；订单净收入口径将成功退款归回原支付日期。',fields:[field('refund_id','STRING','退款事件的唯一编号。'),field('order_id','STRING','对应的原订单。'),field('refund_at','TIMESTAMP','退款事件发生的时间。'),field('amount_cents','BIGINT','退款金额，单位为分。')]},
    {id:'customers',name:'客户明细',physical:'dim.customers',kind:'table',description:'客户注册、首购与渠道归属信息。每名客户一行，客户标识在空间内唯一。',fields:[field('customer_id','STRING','客户唯一标识。'),field('registered_at','TIMESTAMP','账号注册时间。'),field('first_paid_at','TIMESTAMP','首笔订单成功付款时间。')]},
    {id:'products',name:'商品目录',physical:'dim.products',kind:'table',description:'保存商品名称、品类和当前销售状态。每个商品一行，与订单明细中的商品标识关联。',fields:[field('product_id','STRING','商品唯一标识。'),field('product_name','STRING','商品展示名称。'),field('category','STRING','经营分析使用的商品品类。')]},
    {id:'channels',name:'渠道日汇总',physical:'mart.channel_daily',kind:'table',description:'按自然日和订单来源渠道汇总收入与订单数。每个日期、每个渠道一行。',fields:[field('day','DATE','统计日期。'),field('channel','STRING','订单来源渠道。'),field('net_revenue_cents','BIGINT','该渠道的当日净收入，单位为分。')]},
    {id:'revenue',name:'支付归属净收入',physical:'收入指标',kind:'metric',description:'在选定付款期间内，成功支付金额减去截至统计日已成功退款的金额。退款归回原支付期间，排除测试订单。'},
    {id:'paid-orders',name:'支付订单数',physical:'交易指标',kind:'metric',description:'选定付款期间内，成功支付且非测试的订单去重数量。退款不减少已支付订单数。'},
    {id:'repurchase',name:'客户复购率',physical:'客户指标',kind:'metric',description:'统计期间内下单的老客户数，除以该期间全部下单客户数。老客户指此前已有成功支付记录的客户。'},
    {id:'revenue-doc',name:'收入与退款口径说明',physical:'经营分析 · 业务文档',kind:'document',description:'统一付款归属、跨月退款与金额单位的计算规则。'},
    {id:'channel-doc',name:'渠道分类说明',physical:'渠道分析 · 业务文档',kind:'document',description:'说明 App、小程序、网页和合作渠道的归属规则。'},
    {id:'customer-doc',name:'新客与老客判断规则',physical:'客户分析 · 业务文档',kind:'document',description:'按首次成功付款时间判断新客与老客。'},
  ];
  const memoryItems = [
    {id:'money',name:'收入金额统一使用元',description:'收入分析默认换算为元，保留两位小数。',scope:'收入分析',updated:'今天 09:42',enabled:true,content:'涉及收入、退款和客单价时，输出金额统一用元，保留两位小数。原始字段为分时先除以 100，不改变正式指标口径。'},
    {id:'tests',name:'经营分析排除测试订单',description:'统计真实经营表现时，过滤测试订单。',scope:'订单分析',updated:'昨天 16:20',enabled:true,content:'分析经营收入、渠道表现和订单量时，默认排除 is_test_order = 1 的记录。如果需要检查测试订单，应单独说明。'},
    {id:'refund-correction',name:'退款归回原付款月份',description:'净收入按付款日归属，跨月退款不算当月新支出。',scope:'净收入',updated:'10 月 8 日',enabled:true,content:'上次对话确认：这里讨论的净收入使用付款归属口径。2 月退款的 1 月订单，其退款金额归回 1 月。现金流分析需要另行选择事件时间口径。'},
    {id:'output',name:'周报先给结论，再展开数据',description:'简要说明变化、原因和需要继续核实的部分。',scope:'周报',updated:'10 月 7 日',enabled:true,content:'周报阅读时，先展示关键结论，然后给数据和依据。没有验证的原因应标注为待调查，不写成确定结论。'},
    {id:'dates',name:'月份使用自然月',description:'“上月”按完整自然月理解，包含起日、不含次月起日。',scope:'时间范围',updated:'10 月 5 日',enabled:true,content:'月份默认是自然月。查询时间区间使用大于等于月初、小于下月月初。明确说最近 30 天时，使用滚动窗口。'},
    {id:'old-report',name:'旧版汇报格式',description:'按部门拆分的汇报顺序，当前已不再使用。',scope:'周报',updated:'9 月 28 日',enabled:false,content:'先列部门，再展开经营指标。该格式已停用，保留作为历史参考。'},
  ];
  const methodContent = '1. 确认分析时段、渠道和金额单位。\n2. 查看收入指标口径，核对付款归属与退款规则。\n3. 输出 SQL 和关键条件；用户明确要求执行后再查询。\n4. 展示结论、10 行结果预览、最终 SQL 和下载入口。\n5. 发现异常时先提出待核实的问题，不直接认定原因。';
  const skillItems = [
    {id:'income',name:'收入概览',description:'核对口径，比较收入与订单表现，整理成可汇报的结论。',scope:'收入分析',updated:'今天 10:05',enabled:true,content:methodContent},
    {id:'refund-review',name:'退款变化分析',description:'区分付款归属与退款发生时间，定位变化集中在哪些订单。',scope:'退款分析',updated:'昨天 15:24',enabled:true,content:'1. 确认看净收入还是现金流。\n2. 按对应时间字段汇总退款金额。\n3. 按渠道和商品品类拆分变化。\n4. 给出 SQL，等待用户通过聊天明确要求执行。'},
    {id:'weekly',name:'经营周报',description:'用固定结构汇总收入、渠道、退款与后续问题。',scope:'周报',updated:'10 月 8 日',enabled:true,content:'1. 确认本周与对比周的完整时间。\n2. 对齐各项指标单位和过滤条件。\n3. 先给三个主要结论，再展示表格和依据。\n4. 未证实的原因单独列为后续调查。'},
    {id:'channel',name:'渠道对比',description:'在相同时间和口径下，比较各渠道的收入与订单量。',scope:'渠道分析',updated:'10 月 6 日',enabled:true,content:'1. 按渠道汇总净收入和支付订单数。\n2. 比较占比与单位订单收入。\n3. 小样本渠道谨慎解释，不归因为渠道质量。'},
  ];
  const publicItems = [{...skillItems[0],id:'public-income',name:'团队月度收入复盘',description:'团队共享的月度复盘方法，统一净收入口径和汇报结构。',scope:'经营分析',owner:'Alice',updated:'10 月 8 日'},{...skillItems[1],id:'public-refund',name:'退款异常排查',description:'从金额、订单量和退款时效检查异常，逐步缩小调查范围。',scope:'退款分析',owner:'林知夏',updated:'10 月 6 日'}];
  const templates = [
    {name:'收入概览',icon:'metric',description:'核对收入、订单与变化',scope:'收入分析',content:methodContent},
    {name:'退款分析',icon:'search',description:'区分归属，定位异常',scope:'退款分析',content:skillItems[1].content},
    {name:'结果汇报',icon:'document',description:'结论、数据与后续问题',scope:'经营汇报',content:skillItems[2].content},
  ];
  const docs = {
    'revenue-doc':{intro:'本文说明经营分析中“支付归属净收入”的计算方式。订单收入、退款和金额单位应使用同一套约定。',sections:[['定义与用途','净收入表示已收取的实际支付金额，减去截至统计日已成功退款的金额。用于复盘订单带来的收入，不用于直接核算当月现金流。'],['时间归属','订单以首次成功付款的日期归属月份。查询 1 月时，使用 1 月 1 日（含）到 2 月 1 日（不含）的时间范围。'],['跨月退款','1 月付款、2 月成功退款的订单，其退款归回 1 月。随着退款继续发生，历史月份的净收入可能变化；汇报时应说明数据截止日期。'],['金额与过滤','原始金额以分存储，展示时除以 100，单位为元，保留两位小数。排除测试订单以及未成功支付的记录。'],['常见问题','如果问题是“本月实际到账与退款多少”，应使用支付和退款流水的事件发生时间，分别计算流入与流出。不要复用付款归属口径。']]},
    'channel-doc':{intro:'渠道以订单首次提交时记录的来源为准，后续支付入口变化不会覆盖原渠道。',sections:[['渠道分类','App 表示原生应用内提交的订单；小程序、网页和合作渠道独立统计。'],['归属规则','同一订单只归属一个渠道。跨入口付款时仍沿用订单提交渠道，避免重复统计。'],['缺失值','渠道缺失时单列“未知渠道”，不能默认归入 App。修正来源后，再更新相关统计。']]},
    'customer-doc':{intro:'客户的新老属性由首次成功付款时间与分析窗口的关系决定。',sections:[['新客定义','首次成功付款时间处于分析窗口内的客户，计为窗口内新客。'],['老客定义','分析窗口之前已有成功付款记录、且窗口内再次付款的客户，计为老客。'],['去重规则','以客户标识去重。同一客户的多笔订单不会增加客户人数。']]},
  };
  const conversationHistory = [...document.querySelectorAll('.history-item')].map(node => ({id:node.dataset.id,name:node.childNodes[0].textContent,time:node.querySelector('span').textContent}));
  const state = {view:'workbench',object:'orders',tab:'overview',assetTab:'memories',directoryFilter:'all',directorySearch:'',assetSearch:'',conversation:'revenue',newConversation:false,selectedSkill:null,model:'flash',thinking:'high',messages:[],queries:[],resultView:'table',editing:null,documentDrafts:{}};
  let lastRoute = ''; let dialogOrigin = null; let discardAction = null; let toastTimer;
  const dialog = $('#detail-dialog'); const discardDialog = $('#discard-dialog');
  function toast(message) {$('#toast').innerHTML=icon('check')+`<span>${esc(message)}</span>`;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3000);}
  function objectById(id=state.object){return objects.find(item=>item.id===id)||objects[0];}
  function currentAssets(){return state.assetTab==='memories'?memoryItems:state.assetTab==='public'?publicItems:skillItems;}
  function highlightedSql(text){return esc(text).replace(/\b(SELECT|SUM|COUNT|DISTINCT|FROM|WHERE|AND|GROUP BY|ORDER BY|AS)\b/g,'<span class="sql-key">$1</span>');}
  function sqlBlock(value=sql,label='最终执行的 SQL'){return `<div class="sql-block"><div class="sql-heading"><span class="sql-label">${icon('code')}${label}</span><button class="text-button" data-action="copy-sql">${icon('copy')}复制</button></div><pre tabindex="0" aria-label="${label}"><code>${highlightedSql(value)}</code></pre></div>`;}
  function assistant(body, extra=''){return `<article class="assistant-message"><div class="assistant-byline"><span class="assistant-logo">${icon('spark')}</span>Data Agent</div><div class="message-body">${body}</div>${extra}</article>`;}
  function userMessage(text,time='10:24'){return `<article class="user-message"><div class="user-bubble">${esc(text)}</div><span class="message-time">${time}</span></article>`;}
  function resultTable(){return `<div class="table-scroll" tabindex="0" aria-label="查询结果，预览前十行"><table class="data-table"><thead><tr><th class="row-index">#</th><th>付款日期</th><th class="number">净收入（元）</th><th class="number">支付订单数</th></tr></thead><tbody>${rows.slice(0,10).map((row,index)=>`<tr><td class="row-index">${index+1}</td><td>${row.date}</td><td class="number">${money(row.cents)}</td><td class="number">${row.orders}</td></tr>`).join('')}</tbody></table></div><div class="table-footnote"><span>预览 10 行，共 31 行</span></div>`;}
  function resultChart(){const values=rows.map(row=>row.cents/100),max=Math.ceil(Math.max(...values)/1000)*1000;const pts=values.map((value,index)=>`${49+index*18.8},${174-value/max*148}`);return `<div class="chart-wrap"><div class="chart-heading"><span>每日净收入</span><span>单位：元</span></div><svg class="trend-chart" viewBox="0 0 640 220" role="img" aria-label="1 月每天净收入趋势，横轴为付款日期，纵轴为元"><title>1 月 App 每日净收入</title>${[0,.5,1].map(level=>`<line x1="49" y1="${174-level*148}" x2="613" y2="${174-level*148}" stroke="#e9edf3"/><text class="chart-axis" x="4" y="${178-level*148}">${Math.round(max*level).toLocaleString()}</text>`).join('')}<path d="M${pts.join(' L')} L613,174 L49,174 Z" fill="#eaf1fe" opacity=".75"/><polyline points="${pts.join(' ')}" stroke="#567dbe" fill="none" stroke-width="2" stroke-linejoin="round"/>${[0,9,19,30].map(index=>`<text class="chart-axis" x="${49+index*18.8}" y="203" text-anchor="middle">1 月 ${index+1} 日</text>`).join('')}</svg></div>`;}
  function result(){return `<section class="result-section" aria-label="一月 App 净收入查询结果"><div class="result-heading"><div><div class="result-value-label">1 月 App 净收入</div><div class="result-value">128,436.50<small>元</small></div></div><div><div class="result-status">${icon('check')}查询完成</div><small class="quiet-text" style="display:block;color:var(--muted);font-size:11px;margin-top:5px">31 行 · 2.3 秒</small></div></div><div class="result-controls"><div class="segmented" role="tablist" aria-label="结果展示"><button role="tab" aria-selected="${state.resultView==='table'}" data-action="result-view" data-value="table">数据</button><button role="tab" aria-selected="${state.resultView==='chart'}" data-action="result-view" data-value="chart">趋势</button></div><div class="result-actions"><button class="text-button" data-action="show-sql">${icon('code')}最终 SQL</button><button class="text-button" data-action="download">${icon('download')}下载全部数据</button></div></div><div id="result-content">${state.resultView==='table'?resultTable():resultChart()}</div></section>`;}
  function renderConversation(){
    let html='';
    if(state.newConversation){html=`<div class="welcome"><h1>今天想了解哪些数据？</h1><p>从一个问题开始，也可以直接贴入 SQL。</p><div class="starter-list"><button data-action="starter" data-text="帮我看看 1 月 App 的净收入，排除测试订单">1 月 App 的净收入是多少？${icon('arrow')}</button><button data-action="starter" data-text="解释一下支付归属净收入和现金流的区别">解释一个指标的计算口径${icon('arrow')}</button><button data-action="starter" data-text="帮我写一段按渠道统计收入的 SQL">帮我写一段查询 SQL${icon('arrow')}</button></div></div>`;}
    else if(state.conversation==='revenue'){
      html=`<div class="conversation-date">今天 · 10:24</div>${userMessage('帮我看看 1 月 App 每天的净收入，金额用元，排除测试订单。执行后给我结果。')}${assistant('1 月 App 的净收入合计为 <strong>128,436.50 元</strong>。以下按付款日期汇总，已扣除成功退款，并排除了测试订单。',`<div class="condition-line"><span>2026 年 1 月</span><span>App 渠道</span><span>付款归属口径</span><button class="link-button" data-action="evidence">查看口径依据</button></div>${result()}${sqlBlock()}<button class="evidence-link" data-action="evidence">${icon('book')}依据：支付归属净收入 · 收入与退款口径说明${icon('chevron')}</button>`)}`;
    }else{const item=conversationHistory.find(item=>item.id===state.conversation);html=`<div class="conversation-date">${esc(item?.time||'今天')}</div>${userMessage(item?.name||'继续分析')}${assistant('付款归属净收入和现金流使用不同的时间口径。<strong>净收入按原付款日期归属</strong>，现金流按实际收付款时间统计。',`<div class="document-callout">例如 1 月付款、2 月退款：净收入会更新 1 月的金额；现金流则记录 2 月的退款支出。</div><button class="evidence-link" data-action="evidence">${icon('book')}查看完整口径说明${icon('chevron')}</button>`)}`;}
    html+=state.messages.map(item=>item.kind==='user'?userMessage(item.text,'刚刚'):assistant(item.text,item.sql?sqlBlock(sql,'待查询的 SQL'):item.result?result():item.query?queryMarkup(item.query):'')).join('');
    $('#conversation').innerHTML=html;updateRunningDock();
  }
  function queryMarkup(id){const query=state.queries.find(item=>item.id===id);if(!query)return '';if(query.status==='running')return `<div class="running-inline" id="query-${query.id}"><span class="spinner"></span><span>${esc(query.name)} · 正在查询</span><button class="text-button" data-action="stop-query" data-id="${query.id}">${icon('stop')}停止</button></div>`;if(query.status==='stopped')return `<div class="running-inline"><span>${icon('stop')}</span><span>这条查询已停止，其他对话和查询不受影响。</span></div>`;return `<div class="running-inline"><span class="loading-complete">${icon('check')}</span><span>${esc(query.name)}已完成</span><button class="link-button" data-action="query-result" data-id="${query.id}">查看结果</button></div>`;}
  function updateRunningDock(){const running=state.queries.filter(item=>item.status==='running'&&item.conversation===state.conversation);$('#running-dock').innerHTML=running.map(query=>`<div class="running-dock-item"><span class="spinner"></span><span>${esc(query.name)}正在执行，可以继续聊天</span><button class="text-button" data-action="stop-query" data-id="${query.id}">${icon('stop')}停止</button></div>`).join('');}
  function preserveConversationScroll(fn){const container=$('#conversation-scroll'),top=container.scrollTop;fn();container.scrollTop=top;}
  function appendMessages(){state.newConversation=false;preserveConversationScroll(renderConversation);requestAnimationFrame(()=>{$('#conversation-scroll').scrollTop=$('#conversation-scroll').scrollHeight;});}
  function sendMessage(){const input=$('#message-input'),text=input.value.trim();if(!text)return;state.messages.push({kind:'user',text});input.value='';resizeComposer();
    if(/执行|查询结果|跑一下/.test(text)){
      const query={id:String(Date.now()),name:'1 月 App 每日净收入',conversation:state.conversation,status:'running'};state.queries.push(query);state.messages.push({kind:'assistant',text:'查询已开始。你可以继续补充其他问题，结果会回到这条对话。',query:query.id});query.timer=setTimeout(()=>{if(query.status==='running'){query.status='complete';preserveConversationScroll(renderConversation);toast('查询完成 · 可以查看结果');}},18000);
    }else if(/口径|退款|含义/.test(text)){state.messages.push({kind:'assistant',text:'这份结果使用<strong>付款归属口径</strong>：成功退款归回原付款月份。如果你要看现金流，需要按退款实际发生日期统计。<br><button class="link-button" data-action="evidence">查看完整依据</button>'});}
    else{state.messages.push({kind:'assistant',text:'已按 1 月、App 渠道和排除测试订单整理查询。金额换算为元，按付款日期汇总。你可以继续补充条件，或告诉我“执行这条”。',sql:true});}
    appendMessages();input.focus();
  }
  function renderKnowledge(){const obj=objectById();const typeLabel={table:'数据表',metric:'指标',document:'业务文档'}[obj.kind];const tabs=obj.kind==='table'?[['overview','概览'],['fields','字段',obj.fields.length],['metrics','指标',2],['documents','业务文档',1],['changes','维护记录']]:obj.kind==='document'?[['overview','正文'],['changes','维护记录']]:[['overview','指标口径'],['sql','计算 SQL'],['changes','维护记录']];if(!tabs.some(([id])=>id===state.tab))state.tab='overview';
    $('#knowledge-view').innerHTML=`<div class="page-heading"><div><h1>语义管理</h1></div><div class="actions"><button class="button mobile-directory-toggle" data-action="directory">${icon('layers')}目录</button><button class="button" data-action="new-knowledge">${icon('plus')}新建</button><button class="icon-button" data-action="maintenance" aria-label="语义维护操作">${icon('more')}</button></div></div><div class="knowledge-layout"><aside class="knowledge-directory" aria-label="语义对象目录"><label class="search-box">${icon('search')}<input id="knowledge-search" placeholder="搜索表、指标、文档" aria-label="搜索语义对象" value="${esc(state.directorySearch)}"></label><div class="directory-filter"><select id="directory-filter" aria-label="筛选对象类型"><option value="all">全部类型</option><option value="table">数据表</option><option value="metric">指标</option><option value="document">业务文档</option></select><span id="directory-count">${objects.length} 个对象</span></div><div class="directory-list" id="directory-list"></div></aside><div class="knowledge-detail" id="knowledge-detail"><div class="detail-breadcrumb">零售分析空间<span>/</span>${typeLabel}</div><div class="detail-title"><div><h2>${esc(obj.name)}</h2><div class="physical-name">${esc(obj.physical)}</div></div><button class="button" data-action="edit-object">${icon('edit')}编辑</button></div><div class="meta-line"><span><span class="tiny-avatar">A</span>Alice 负责</span><span>今天 09:42 更新</span><span class="status-label">${icon('check')}已核对</span></div><div class="tabs" role="tablist" aria-label="语义详情">${tabs.map(([id,label,count])=>`<button role="tab" tabindex="${state.tab===id?0:-1}" aria-selected="${state.tab===id}" data-action="knowledge-tab" data-id="${id}">${label}${count?`<span>${count}</span>`:''}</button>`).join('')}</div><div id="knowledge-panel" role="tabpanel">${knowledgeContent(obj)}</div></div></div>`;
    $('#directory-filter').value=state.directoryFilter;renderDirectory();
  }
  function renderDirectory(){const matches=objects.filter(item=>(state.directoryFilter==='all'||item.kind===state.directoryFilter)&&`${item.name} ${item.physical}`.toLowerCase().includes(state.directorySearch.toLowerCase()));$('#directory-count').textContent=`${matches.length} 个对象`;$('#directory-list').innerHTML=['table','metric','document'].map(kind=>{const list=matches.filter(item=>item.kind===kind);return !list.length?'':`<div class="directory-label">${{table:'数据表',metric:'指标',document:'业务文档'}[kind]} · ${list.length}</div>${list.map(item=>`<a class="directory-item" href="#knowledge/${item.id}/overview" aria-current="${state.object===item.id}">${icon(kind)}<span><strong>${esc(item.name)}</strong><small>${esc(item.physical)}</small></span></a>`).join('')}`;}).join('')||'<div class="empty-state"><p>没有找到相关内容</p></div>';}
  function knowledgeContent(obj){if(state.tab==='changes')return `<h3>最近维护</h3><div class="timeline-row"><span>今天 09:42</span><div>Alice 更新了${obj.kind==='document'?'业务说明':'口径说明'}<p>补充退款归属与金额单位的使用约定</p></div></div><div class="timeline-row"><span>10 月 8 日</span><div>Alice 完成人工核对<p>已核对来源资料与相关 SQL</p></div></div><details class="metadata-details"><summary>查看来源与维护信息</summary><p>表信息来自 Datasight 元数据与节点 SQL；人工维护的说明单独保留。后续来源同步不会覆盖人工修改。</p></details>`;
    if(obj.kind==='document')return documentContent(obj.id);
    if(obj.kind==='metric'){if(state.tab==='sql')return `<p class="definition">按付款日和渠道汇总，使用订单收入明细中的已分摊金额。</p>${sqlBlock(sql,'指标计算 SQL')}`;return `<p class="definition">${esc(obj.description)}</p><div class="document-formula">${obj.id==='revenue'?'净收入 = 成功支付金额 − 成功退款金额':obj.id==='paid-orders'?'支付订单数 = 成功支付的订单去重数':'复购率 = 下单老客户数 ÷ 全部下单客户数'}</div><dl class="fact-grid"><div><dt>时间字段</dt><dd>首次成功付款日期</dd></div><div><dt>默认单位</dt><dd>${obj.id==='revenue'?'元，保留两位小数':obj.id==='paid-orders'?'单':'百分比'}</dd></div><div><dt>默认过滤</dt><dd>排除测试订单</dd></div><div><dt>数据来源</dt><dd><a class="link-button" href="#knowledge/orders/overview">订单收入明细</a></dd></div></dl><h3>业务说明</h3><a class="related-row" href="#knowledge/revenue-doc/overview">${icon('document')}<div><strong>收入与退款口径说明</strong><p>查看时间归属、跨月退款与常见问题</p></div>${icon('chevron')}</a>`;}
    if(state.tab==='fields')return `<label class="search-box field-search">${icon('search')}<input id="field-search" aria-label="搜索字段" placeholder="搜索字段名或含义"></label><table class="field-table"><thead><tr><th>字段</th><th>业务含义</th><th><span class="sr-only">操作</span></th></tr></thead><tbody id="field-rows">${fieldRows(obj.fields)}</tbody></table>`;
    if(state.tab==='metrics')return `<p class="definition">通过这张表计算的指标</p>${['revenue','paid-orders'].map(id=>{const metric=objectById(id);return `<a class="related-row" href="#knowledge/${id}/overview">${icon('metric')}<div><strong>${metric.name}</strong><p>${metric.description}</p></div>${icon('chevron')}</a>`;}).join('')}`;
    if(state.tab==='documents')return `<a class="related-row" href="#knowledge/revenue-doc/overview">${icon('document')}<div><strong>收入与退款口径说明</strong><p>整篇阅读付款归属、退款处理和金额规则</p></div>${icon('chevron')}</a>`;
    return `<div class="section-label" style="margin-top:0"><h3>这张表记录什么</h3></div><p class="definition">${esc(obj.description)}</p><dl class="fact-grid"><div><dt>一行代表</dt><dd>${obj.id==='orders'?'一个订单商品行':obj.id==='payments'?'一次支付事件':obj.id==='refunds'?'一次退款事件':obj.id==='customers'?'一名客户':obj.id==='products'?'一个商品':'一天、一个渠道'}</dd></div><div><dt>主要时间</dt><dd>${obj.id==='orders'?'付款日期':obj.id==='payments'?'支付事件发生时间':'记录对应的业务日期'}</dd></div><div><dt>金额单位</dt><dd>原始为分，展示换算为元</dd></div><div><dt>使用时注意</dt><dd>经营分析排除测试订单</dd></div></dl><div class="section-label"><h3>常用字段</h3><button class="link-button" data-action="knowledge-tab" data-id="fields">查看全部 ${obj.fields.length} 个字段</button></div><table class="field-table"><thead><tr><th>字段</th><th>业务含义</th><th><span class="sr-only">操作</span></th></tr></thead><tbody>${fieldRows(obj.fields.slice(0,4))}</tbody></table><div class="section-label"><h3>相关指标与文档</h3></div><a class="related-row" href="#knowledge/revenue/overview">${icon('metric')}<div><strong>支付归属净收入</strong><p>支付金额扣除退款，按原付款日期归属</p></div>${icon('chevron')}</a><a class="related-row" href="#knowledge/revenue-doc/overview">${icon('document')}<div><strong>收入与退款口径说明</strong><p>查看完整的业务约定</p></div>${icon('chevron')}</a><details class="metadata-details"><summary>来源与维护信息</summary><p>已汇总 Datasight 元数据、节点 SQL 和人工说明。当前表的负责人来自 Datasight 维护人。</p></details>`;
  }
  function fieldRows(fields){return fields.map(item=>`<tr><td><code>${esc(item.name)}</code><small>${item.type}</small></td><td>${esc(item.meaning)}</td><td><button class="icon-button" data-action="edit-field" data-name="${item.name}" aria-label="编辑 ${item.name}">${icon('edit')}</button></td></tr>`).join('');}
  function documentContent(id){if(state.documentDrafts[id])return `<div class="document-content">${renderDocumentText(state.documentDrafts[id])}</div>`;const doc=docs[id]||docs['revenue-doc'];return `<nav class="document-toc" aria-label="文章目录">${doc.sections.map(([title],index)=>`<a href="#" data-action="doc-section" data-index="${index}">${title}</a>`).join('')}</nav><article class="document-content"><p>${doc.intro}</p>${doc.sections.map(([title,text],index)=>`<h3 id="doc-section-${index}">${title}</h3><p>${text}</p>`).join('')}</article>`;}
  function renderDocumentText(text){return esc(text).split('\n\n').map(part=>part.startsWith('## ')?`<h3>${part.slice(3)}</h3>`:`<p>${part.replace(/\n/g,'<br>')}</p>`).join('');}
  function renderAssets(){const isMemory=state.assetTab==='memories',isPublic=state.assetTab==='public';$('#assets-view').innerHTML=`<div class="page-heading"><div><h1>我的积累</h1></div><button class="button primary" data-action="new-asset">${icon(isPublic?'publish':'plus')}${isPublic?'发布分析方法':isMemory?'新增记忆':'新建 Skill'}</button></div><div class="asset-content"><div class="tabs" role="tablist" aria-label="个人与公共资产"><button role="tab" tabindex="${isMemory?0:-1}" aria-selected="${isMemory}" data-action="asset-tab" data-id="memories">个人记忆<span>${memoryItems.length}</span></button><button role="tab" tabindex="${state.assetTab==='skills'?0:-1}" aria-selected="${state.assetTab==='skills'}" data-action="asset-tab" data-id="skills">我的 Skill<span>${skillItems.length}</span></button><button role="tab" tabindex="${isPublic?0:-1}" aria-selected="${isPublic}" data-action="asset-tab" data-id="public">空间公共 Skill<span>${publicItems.length}</span></button></div>${isPublic?`<div class="asset-info">${icon('globe')}本空间成员可以选用。发布会创建独立的公共副本，由负责人维护。</div>`:!isMemory?'<p class="asset-description">Skill 是可重复使用的分析方法。选用后，它会为当前对话提供分析步骤与注意事项。</p>':''}<div class="asset-toolbar"><label class="search-box">${icon('search')}<input id="asset-search" aria-label="搜索资产" placeholder="${isMemory?'搜索记忆名称、内容或范围':'搜索分析方法'}" value="${esc(state.assetSearch)}"></label><span class="asset-count" id="asset-count"></span></div><div class="asset-list-header"><span>${isMemory?'记忆':'分析方法'}</span><span class="asset-scope">${isPublic?'负责人':'适用范围'}</span><span class="status-column">状态</span><span class="asset-time">最近更新</span><span></span></div><div id="asset-list"></div></div>`;renderAssetList();}
  function renderAssetList(){const items=currentAssets().filter(item=>`${item.name} ${item.description} ${item.scope}`.includes(state.assetSearch));$('#asset-count').textContent=`${items.length} 条${state.assetTab==='memories'?'记忆':'方法'}`;$('#asset-list').innerHTML=items.map(item=>`<div class="asset-row" tabindex="0" role="button" data-action="asset-detail" data-id="${item.id}" aria-label="查看${esc(item.name)}"><div class="asset-name"><span class="asset-icon">${icon(state.assetTab==='memories'?'memory':state.assetTab==='public'?'globe':'spark')}</span><div><h3>${esc(item.name)}</h3><p>${esc(item.description)}</p></div></div><span class="asset-scope">${esc(state.assetTab==='public'?item.owner:item.scope)}</span><span class="status-column"><span class="status-label ${item.enabled?'':'neutral'}">${item.enabled?'已启用':'已停用'}</span></span><span class="asset-time">${item.updated}</span><span class="icon-button" aria-hidden="true">${icon('chevron')}</span></div>`).join('')||`<div class="empty-state">${icon('search')}<h3>没有找到相关${state.assetTab==='memories'?'记忆':'分析方法'}</h3><p>试试更短的关键词，或按适用范围搜索。</p><button class="button" data-action="clear-search">清空搜索</button></div>`;}
  function modal(title,subtitle,body,footer='',narrow=false){state.editing=null;dialogOrigin=document.activeElement;$('#dialog-content').innerHTML=`<header class="modal-header"><div><h2 id="modal-title">${esc(title)}</h2>${subtitle?`<p>${subtitle}</p>`:''}</div><button class="icon-button" data-action="close-modal" aria-label="关闭">${icon('close')}</button></header><div class="modal-content">${body}</div>${footer?`<footer class="modal-footer">${footer}</footer>`:''}`;dialog.setAttribute('aria-labelledby','modal-title');dialog.classList.toggle('narrow',narrow);dialog.classList.remove('skill-editor');if(!dialog.open)dialog.showModal();}
  function closeModal(){state.editing=null;dialog.close();if(dialogOrigin?.isConnected)dialogOrigin.focus();}
  function requestClose(after){if(state.editing?.dirty){discardAction=()=>{closeModal();if(after)after();};discardDialog.showModal();$('#keep-editing').focus();}else{closeModal();if(after)after();}}
  function showEvidence(){modal('支付归属净收入','收入指标 · 订单收入明细',`<div class="evidence-meta"><span><span class="tiny-avatar">A</span>Alice 负责</span><span class="status-label">${icon('check')}已核对</span></div><h3>共享口径</h3><p class="definition" style="margin-top:10px">成功支付金额减去截至统计日已成功退款的金额。退款归回原付款月份。</p><div class="document-formula">净收入 = 成功支付金额 − 成功退款金额</div><dl class="evidence-grid"><dt>时间归属</dt><dd>首次成功付款日期；跨月退款归回原月</dd><dt>默认过滤</dt><dd>排除测试订单</dd><dt>金额单位</dt><dd>元，保留两位小数</dd></dl><h3 style="margin-top:23px">本次查询条件</h3><dl class="evidence-grid"><dt>时间范围</dt><dd>2026 年 1 月 1 日至 1 月 31 日</dd><dt>渠道</dt><dd>App，由这次提问指定</dd></dl><div class="evidence-source"><strong>收入与退款口径说明</strong>完整说明时间归属、退款处理与常见问题。</div>`,`<button class="text-button" data-action="maintain-evidence">${icon('edit')}去维护此内容</button><span style="flex:1"></span><button class="button primary" data-action="close-modal">${icon('back')}返回对话</button>`,true);}

  function showMethods(publish=false){modal(publish?'发布分析方法':'选用分析方法',publish?'从你的 Skill 创建空间公共副本':'选用后用于当前对话，随时可以移除',`<div class="tabs" role="tablist" style="margin-top:0"><button role="tab" aria-selected="true" data-action="method-scope" data-value="mine">我的 Skill</button>${publish?'':'<button role="tab" aria-selected="false" data-action="method-scope" data-value="public">空间公共 Skill</button>'}</div><div id="method-choices" data-publishing="${publish}">${methodChoices(skillItems,publish)}</div>`,`<span class="modal-footer-note">${publish?'发布后由你负责维护':'只采用本次明确选择的方法'}</span><button class="button" data-action="close-modal">返回</button>`);}
  function methodChoices(items,publish=false){return items.map(item=>`<div class="method-choice"><span class="asset-icon">${icon('spark')}</span><div><h3>${item.name}</h3><p>${item.description}</p></div><button class="button" data-action="${publish?'publish-skill':'choose-skill'}" data-id="${item.id}">${publish?'发布':'选用'}</button></div>`).join('');}
  function renderSelectedSkill(){const skill=[...skillItems,...publicItems].find(item=>item.id===state.selectedSkill);$('#selected-skill').innerHTML=skill?`<div class="skill-chip">${icon('spark')}${skill.name}<button type="button" data-action="remove-skill" aria-label="移除已选分析方法">${icon('close')}</button></div>`:'';}
  function openAssetDetail(id){const item=currentAssets().find(item=>item.id===id);if(!item)return;const isMemory=state.assetTab==='memories',isPublic=state.assetTab==='public';modal(item.name,isMemory?'个人记忆 · 仅你可用':isPublic?'空间公共 Skill':'我的 Skill · 个人分析方法',`<div class="evidence-meta"><span class="status-label ${item.enabled?'':'neutral'}">${item.enabled?'已启用':'已停用'}</span><span>${item.updated}更新</span></div><div class="asset-detail-label">${isMemory?'记住的内容':'分析步骤'}</div><div class="method-content">${esc(item.content)}</div><div class="asset-detail-label">适用范围</div><p class="asset-detail-title">${esc(item.scope)}</p><details class="metadata-details"><summary>来源与维护信息</summary><p>${isMemory?'来自你明确保存的偏好与纠错，仅用于你的对话。':`负责人：${esc(item.owner||'Alice')}。${isPublic?'空间成员可以选用，修改由负责人或超级维护者完成。':'发布到公共空间前仅自己可用。'}`}</p></details>`,`<button class="text-button" data-action="toggle-asset" data-id="${id}">${item.enabled?'停用':'启用'}</button><span style="flex:1"></span>${!isMemory?`<button class="button" data-action="choose-skill" data-id="${id}">用于对话</button>`:''}<button class="button primary" data-action="edit-asset" data-id="${id}">${icon('edit')}编辑</button>`);}
  function documentText(id){if(state.documentDrafts[id])return state.documentDrafts[id];const doc=docs[id]||docs['revenue-doc'];return `${doc.intro}\n\n${doc.sections.map(([title,text])=>`## ${title}\n\n${text}`).join('\n\n')}`;}
  function startEditor(kind,item=null){const fresh=!item||item.fresh;const isSkill=kind==='skill',isDoc=kind==='document',isField=kind==='field',isObject=kind==='object';const title=isSkill?(fresh?'新建分析方法':'编辑分析方法'):isDoc?(fresh?'新建业务文档':'编辑业务文档'):kind==='metric'?'新建指标口径':isField?`编辑字段含义`:(isObject?'编辑表说明':fresh?'新增个人记忆':'编辑个人记忆');const name=item?.name||'',content=isDoc?(fresh?'':documentText(item.id)):item?.content||item?.meaning||item?.description||'',scope=item?.scope||'';
    modal(title,isField?esc(name):isSkill?'保存为你的个人 Skill，可在对话中选用':isDoc?'整篇维护，保存后更新正文':'保存后更新当前内容',`${isSkill&&fresh?`<div id="template-region"><div class="template-label">从模板开始</div><div class="templates">${templates.map((template,index)=>`<button class="template-button" data-action="apply-template" data-index="${index}">${icon(template.icon)}<strong>${template.name}</strong><small>${template.description}</small></button>`).join('')}</div></div>`:''}<form id="editor-form"><label class="form-field" ${isField?'hidden':''}><span>名称<small>必填</small></span><input name="name" id="editor-name" value="${esc(name)}" placeholder="给它一个容易找到的名字" ${isField?'':'required'}></label>${isDoc?'<div class="document-mode segmented"><button type="button" data-action="document-mode" data-value="edit" aria-selected="true">编辑</button><button type="button" data-action="document-mode" data-value="preview" aria-selected="false">阅读预览</button></div>':''}<label class="form-field" id="editor-content-field"><span>${isField?'业务含义':isSkill?'分析步骤与注意事项':isDoc?'文档正文':kind==='metric'?'定义与计算口径':isObject?'这张表记录什么':'记住的内容'}<small>必填</small></span><textarea id="editor-body" name="content" class="${isDoc?'document-editor':''}" required>${esc(content)}</textarea>${isField?'<small>说明字段代表什么，以及使用时需要注意的单位、取值或时间含义。</small>':''}</label><div id="document-preview" class="document-content" hidden></div>${isSkill||kind==='memory'?`<label class="form-field"><span>适用范围<small>必填</small></span><input id="editor-scope" name="scope" value="${esc(scope)}" placeholder="例如：月度收入分析" required></label>`:''}${isSkill?'<label class="check-label"><input type="checkbox" name="verified">我已核对内容 <span style="color:var(--muted)">（可选）</span></label>':''}<p class="error-message" id="editor-error" hidden></p></form>`,`<span class="modal-footer-note" id="editor-state">${isField||isObject||isDoc?'人工修改会单独保留':'仅自己可用，可随时编辑'}</span><button class="button" data-action="close-modal">取消</button><button class="button primary" data-action="save-editor">保存${isSkill?' Skill':'修改'}</button>`);
    dialog.classList.toggle('skill-editor',isSkill);state.editing={kind,item,dirty:false,fresh};
  }
  function markDirty(){if(!state.editing)return;state.editing.dirty=true;$('#editor-state').textContent='有未保存的修改';$('#editor-state').classList.add('unsaved-indicator');}
  function saveEditor(){const edit=state.editing;if(!edit)return;const form=$('#editor-form');if(!form.reportValidity())return;const values=Object.fromEntries(new FormData(form));if(!values.content.trim()||(!values.name.trim()&&edit.kind!=='field')){$('#editor-error').hidden=false;$('#editor-error').textContent='名称和正文需要填写实际内容。';return;}
    if(edit.kind==='field')edit.item.meaning=values.content.trim();else if(edit.kind==='document'){if(edit.fresh){edit.item={id:'doc-'+Date.now(),kind:'document',physical:'业务文档',name:values.name.trim(),description:values.content.split('\n')[0]};objects.push(edit.item);}else edit.item.name=values.name.trim();state.documentDrafts[edit.item.id]=values.content;}else if(edit.kind==='metric'){objects.push({id:'metric-'+Date.now(),kind:'metric',physical:'自定义指标',name:values.name.trim(),description:values.content});}else if(edit.kind==='object'){edit.item.name=values.name.trim();edit.item.description=values.content.trim();}else{const list=edit.kind==='memory'?memoryItems:skillItems;if(edit.item)Object.assign(edit.item,{name:values.name.trim(),content:values.content,scope:values.scope,updated:'刚刚'});else list.unshift({id:`${edit.kind}-${Date.now()}`,name:values.name.trim(),description:values.content.split('\n')[0].replace(/^\d+\.\s*/,''),content:values.content,scope:values.scope,updated:'刚刚',enabled:true});}
    closeModal();if(state.view==='knowledge')renderKnowledge();if(state.view==='assets')renderAssets();toast('修改已保存');
  }
  function showHistory(){modal('全部对话','查找之前的问题，接着聊',`<label class="search-box history-search">${icon('search')}<input id="history-search" aria-label="搜索全部对话" placeholder="搜索标题或关键词"></label><div id="history-results">${historyRows(conversationHistory)}</div>`,`<button class="button" data-action="close-modal">返回对话</button>`);}
  function historyRows(items){return items.map(item=>`<div class="history-modal-row"><button class="history-open" data-action="open-history" data-id="${item.id}"><strong>${item.name}</strong><small>${item.time} · 零售分析空间</small></button><button class="icon-button" data-action="remove-history" data-id="${item.id}" aria-label="移除对话 ${item.name}">${icon('trash')}</button></div>`).join('')||'<div class="empty-state"><p>没有找到相关对话</p></div>';}
  function download(){const csv='\uFEFF付款日期,净收入（元）,支付订单数\n'+rows.map(row=>`${row.date},${(row.cents/100).toFixed(2)},${row.orders}`).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='1月App每日净收入.csv';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已下载 31 行数据');}
  async function copySql(){try{await navigator.clipboard.writeText(sql);toast('SQL 已复制');}catch{const area=document.createElement('textarea');area.value=sql;document.body.append(area);area.select();const copied=document.execCommand('copy');area.remove();toast(copied?'SQL 已复制':'可在 SQL 区域选中并复制');}}
  function navigate(hash){location.hash=hash;}
  function route(){const parts=location.hash.slice(1).split('/');state.view=['knowledge','assets'].includes(parts[0])?parts[0]:'workbench';state.object=objects.some(item=>item.id===parts[1])?parts[1]:'orders';state.tab=parts[2]||'overview';if(state.view==='assets')state.assetTab=['memories','skills','public'].includes(parts[1])?parts[1]:'memories';if(state.view==='workbench'&&parts[1]){state.conversation=parts[1]==='new'?'new':parts[1];state.newConversation=parts[1]==='new';}lastRoute=location.hash;
    document.querySelectorAll('[data-nav]').forEach(node=>{if(node.dataset.nav===state.view)node.setAttribute('aria-current','page');else node.removeAttribute('aria-current');});$('#workspace-view').hidden=state.view!=='workbench';$('#knowledge-view').hidden=state.view!=='knowledge';$('#assets-view').hidden=state.view!=='assets';$('#breadcrumb-section').textContent={workbench:'工作台',knowledge:'语义管理',assets:'我的积累'}[state.view];$('#breadcrumb-title').textContent=state.view==='workbench'?(state.newConversation?'新对话':conversationHistory.find(item=>item.id===state.conversation)?.name||'1 月 App 收入分析'):'零售分析空间';$('#topbar-actions').innerHTML=state.view==='workbench'?`<button class="text-button" data-action="history">${icon('clock')}<span>会话记录</span></button>`:'<span class="topbar-note">共享知识，个人积累</span>';$('#sidebar').classList.remove('is-open');syncSidebarState();if(state.view==='knowledge')renderKnowledge();else if(state.view==='assets')renderAssets();else renderConversation();}
  function syncSidebarState(){const sidebar=$('#sidebar');sidebar.inert=window.innerWidth<=600&&!sidebar.classList.contains('is-open');$('.mobile-menu').setAttribute('aria-expanded',String(sidebar.classList.contains('is-open')));}
  document.addEventListener('click',event=>{
    if(event.target.closest('.skip-link')){event.preventDefault();$('#main').focus();return;}
    const target=event.target.closest('[data-action]');if(!target)return;const {action,id,value,index}=target.dataset;
    if(['doc-section','asset-detail'].includes(action))event.preventDefault();
    switch(action){
      case 'menu':$('#sidebar').classList.toggle('is-open');syncSidebarState();break;
      case 'new-chat':state.messages=[];state.newConversation=true;state.conversation='new';navigate('workbench/new');if(location.hash==='#workbench/new')route();$('#message-input').focus();break;
      case 'conversation':state.messages=[];state.newConversation=false;state.conversation=id;document.querySelectorAll('.history-item').forEach(node=>node.classList.toggle('selected',node.dataset.id===id));navigate(`workbench/${id}`);break;
      case 'starter':$('#message-input').value=target.dataset.text;resizeComposer();$('#message-input').focus();break;
      case 'copy-sql':copySql();break;
      case 'show-sql':modal('最终执行的 SQL','1 月 App 每日净收入',sqlBlock(),'<button class="button primary" data-action="close-modal">返回结果</button>');break;
      case 'download':download();break;
      case 'result-view':state.resultView=value;preserveConversationScroll(renderConversation);break;
      case 'evidence':showEvidence();break;
      case 'close-modal':requestClose();break;
      case 'maintain-evidence':requestClose(()=>navigate('knowledge/revenue/overview'));break;
      case 'history':showHistory();break;
      case 'open-history':closeModal();state.messages=[];state.conversation=id;state.newConversation=false;navigate(`workbench/${id}`);break;
      case 'remove-history':{const entry=conversationHistory.find(item=>item.id===id);modal('移除这条对话？',esc(entry?.name),'<p class="definition">移除后，这条对话会从当前列表中消失。</p>',`<button class="button" data-action="history">返回列表</button><button class="button danger" data-action="confirm-remove-history" data-id="${id}">移除对话</button>`,true);break;}
      case 'confirm-remove-history':conversationHistory.splice(conversationHistory.findIndex(item=>item.id===id),1);document.querySelector(`.history-item[data-id="${id}"]`)?.remove();showHistory();toast('已从列表移除');break;
      case 'select-skill':showMethods();break;
      case 'method-scope':{const publish=$('#method-choices').dataset.publishing==='true';$('#method-choices').innerHTML=methodChoices(value==='public'?publicItems:skillItems,publish);target.parentElement.querySelectorAll('[role=tab]').forEach(node=>node.setAttribute('aria-selected',String(node===target)));break;}
      case 'choose-skill':state.selectedSkill=id;closeModal();renderSelectedSkill();if(state.view!=='workbench')navigate(`workbench/${state.conversation}`);$('#message-input').focus();toast('分析方法已用于当前对话');break;
      case 'remove-skill':state.selectedSkill=null;renderSelectedSkill();break;
      case 'publish-skill':{const item=skillItems.find(item=>item.id===id);if(!item)break;modal('发布到空间公共 Skill',esc(item.name),`<p class="definition">本空间成员将可以选用这个分析方法。发布会创建一个独立副本，个人版本仍保留。你将成为公共副本的负责人。</p>`,`<button class="button" data-action="new-asset">返回选择</button><button class="button primary" data-action="confirm-publish" data-id="${id}">发布公共副本</button>`,true);break;}
      case 'confirm-publish':{const item=skillItems.find(item=>item.id===id);publicItems.unshift({...item,id:`public-${Date.now()}`,owner:'Alice',updated:'刚刚'});closeModal();renderAssets();toast('公共副本已发布');break;}
      case 'model-info':modal('模型与思考强度','从下一条消息开始使用','<p class="definition">Flash 适合日常查询，Pro 可用于需要更深入推理的问题。较高的思考强度通常需要更多等待时间和用量。</p><p class="definition" style="margin-top:15px">已经开始的回复和查询会沿用原来的设置。</p>','<button class="button primary" data-action="close-modal">知道了</button>',true);break;
      case 'stop-query':{const query=state.queries.find(item=>item.id===id);if(query){clearTimeout(query.timer);query.status='stopped';preserveConversationScroll(renderConversation);toast('这条查询已停止');}break;}
      case 'query-result':modal('1 月 App 每日净收入','查询完成 · 31 行',resultTable()+sqlBlock(),'<button class="button" data-action="download">下载全部数据</button><button class="button primary" data-action="close-modal">返回对话</button>');break;
      case 'directory':$('.knowledge-layout').classList.toggle('directory-visible');break;
      case 'knowledge-tab':navigate(`knowledge/${state.object}/${id}`);break;
      case 'edit-field':startEditor('field',objectById().fields.find(item=>item.name===target.dataset.name));break;
      case 'edit-object':{const obj=objectById();startEditor(obj.kind==='document'?'document':'object',obj);break;}
      case 'doc-section':$(`#doc-section-${index}`)?.scrollIntoView({behavior:'smooth',block:'start'});break;
      case 'asset-tab':state.assetSearch='';navigate(`assets/${id}`);break;
      case 'asset-detail':openAssetDetail(id);break;
      case 'edit-asset':startEditor(state.assetTab==='memories'?'memory':'skill',currentAssets().find(item=>item.id===id));break;
      case 'toggle-asset':{const item=currentAssets().find(item=>item.id===id);item.enabled=!item.enabled;renderAssets();openAssetDetail(id);toast(item.enabled?'已启用':'已停用');break;}
      case 'new-asset':state.assetTab==='public'?showMethods(true):startEditor(state.assetTab==='memories'?'memory':'skill');break;
      case 'clear-search':state.assetSearch='';$('#asset-search').value='';renderAssetList();break;
      case 'save-editor':saveEditor();break;
      case 'apply-template':{const template=templates[Number(index)];$('#editor-name').value=template.name;$('#editor-body').value=template.content;$('#editor-scope').value=template.scope;$('#template-region').innerHTML=`<div class="template-applied">${icon('check')}已采用「${template.name}」<button class="link-button" data-action="change-template">更换模板</button></div>`;markDirty();break;}
      case 'change-template':$('#template-region').innerHTML=`<div class="templates">${templates.map((template,i)=>`<button class="template-button" data-action="apply-template" data-index="${i}">${icon(template.icon)}<strong>${template.name}</strong><small>${template.description}</small></button>`).join('')}</div>`;break;
      case 'document-mode':$('#editor-content-field').hidden=value==='preview';$('#document-preview').hidden=value!=='preview';$('#document-preview').innerHTML=renderDocumentText($('#editor-body').value);target.parentElement.querySelectorAll('button').forEach(node=>node.setAttribute('aria-selected',String(node===target)));break;
      case 'maintenance':modal('语义维护','零售分析空间',`<div class="method-choice">${icon('layers')}<div><h3>来源同步</h3><p>元数据、血缘与节点 SQL 汇总到同一个表对象。</p></div><button class="button" data-action="source-detail">查看来源</button></div><div class="method-choice">${icon('check')}<div><h3>人工维护受保护</h3><p>重新预填不会覆盖已保存的人工修改。</p></div></div>`,'<button class="button" data-action="close-modal">关闭</button>',true);break;
      case 'source-detail':modal('订单收入明细的来源','mart.order_revenue','<ul class="plain-list"><li>Datasight：表结构、维护人和字段类型。</li><li>节点 SQL：加工逻辑、金额分摊和过滤条件。</li><li>人工说明：付款归属、退款处理与适用场景。</li></ul>','<button class="button" data-action="close-modal">关闭</button>',true);break;
      case 'new-knowledge':modal('新建语义内容','独立内容由首次录入的人负责',`<a class="related-row" href="#" data-action="new-document">${icon('document')}<div><strong>业务文档</strong><p>整篇记录一张表或多张表的业务说明</p></div>${icon('chevron')}</a><a class="related-row" href="#" data-action="new-metric">${icon('metric')}<div><strong>指标口径</strong><p>记录定义、条件与计算方式</p></div>${icon('chevron')}</a>`,'<button class="button" data-action="close-modal">取消</button>',true);break;
      case 'new-document':event.preventDefault();startEditor('document',{fresh:true,name:'',id:'new-document'});break;
      case 'new-metric':event.preventDefault();startEditor('metric');break;
      case 'account':modal('Alice','零售分析空间 · 超级维护者','<div class="account-role-description">当前最高角色：<strong>超级维护者</strong><ul><li>可以维护本空间的全部共享语义。</li><li>可以调整指标、文档和公共 Skill 的负责人。</li><li>Datasight 的取数和 SQL 执行权限独立校验。</li></ul></div>','<button class="button primary" data-action="close-modal">关闭</button>',true);break;
    }
  });
  document.addEventListener('input',event=>{const input=event.target;if(input.id==='knowledge-search'){state.directorySearch=input.value;renderDirectory();}if(input.id==='field-search')$('#field-rows').innerHTML=fieldRows(objectById().fields.filter(item=>`${item.name} ${item.meaning}`.toLowerCase().includes(input.value.toLowerCase())));if(input.id==='asset-search'){state.assetSearch=input.value;renderAssetList();}if(input.id==='history-search')$('#history-results').innerHTML=historyRows(conversationHistory.filter(item=>item.name.includes(input.value)));if(input.closest('#editor-form'))markDirty();if(input.id==='message-input')resizeComposer();});
  document.addEventListener('change',event=>{if(event.target.id==='directory-filter'){state.directoryFilter=event.target.value;renderDirectory();}if(event.target.id==='model-select'){state.model=event.target.value;const options=state.model==='flash'?[['off','关闭'],['low','轻度'],['high','深度'],['max','最高']]:[['off','关闭'],['high','深度'],['max','最高']];if(!options.some(([value])=>value===state.thinking))state.thinking='high';$('#thinking-select').innerHTML=options.map(([value,label])=>`<option value="${value}">${label}</option>`).join('');$('#thinking-select').value=state.thinking;toast('模型设置将从下一条消息生效');}if(event.target.id==='thinking-select'){state.thinking=event.target.value;toast('思考强度将从下一条消息生效');}});
  document.addEventListener('keydown',event=>{if(event.target.matches('.asset-row')&&(event.key==='Enter'||event.key===' ')){event.preventDefault();event.target.click();}const tab=event.target.closest('[role=tab]');if(tab&&['ArrowRight','ArrowLeft','Home','End'].includes(event.key)){event.preventDefault();const siblings=[...tab.parentElement.querySelectorAll('[role=tab]')],current=siblings.indexOf(tab),next=event.key==='Home'?0:event.key==='End'?siblings.length-1:(current+(event.key==='ArrowRight'?1:-1)+siblings.length)%siblings.length;const action=siblings[next].dataset.action,id=siblings[next].dataset.id,value=siblings[next].dataset.value;siblings[next].click();requestAnimationFrame(()=>document.querySelector(`[data-action="${action}"][data-${id?'id':'value'}="${id||value}"]`)?.focus());}if(event.target.id==='message-input'&&event.key==='Enter'&&!event.shiftKey&&!event.isComposing){event.preventDefault();sendMessage();}});
  $('#composer-form').addEventListener('submit',event=>{event.preventDefault();sendMessage();});
  dialog.addEventListener('cancel',event=>{event.preventDefault();requestClose();});dialog.addEventListener('click',event=>{if(event.target===dialog){const rect=dialog.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom)requestClose();}});
  $('#keep-editing').addEventListener('click',()=>{discardDialog.close();discardAction=null;$('#editor-body')?.focus();});$('#discard-editing').addEventListener('click',()=>{discardDialog.close();const action=discardAction;discardAction=null;action?.();});
  window.addEventListener('beforeunload',event=>{if(state.editing?.dirty){event.preventDefault();event.returnValue='';}});
  window.addEventListener('hashchange',()=>{if(state.editing?.dirty){const destination=location.hash;window.history.replaceState(null,'',lastRoute);requestClose(()=>navigate(destination));}else route();});
  // 复用预览技能的文本测量，只调整输入框高度，不改写用户输入。
  function resizeComposer(){const input=$('#message-input');if(window.Pretext&&document.fonts.status==='loaded'){const style=getComputedStyle(input),width=Math.max(160,input.clientWidth-8),font=`${style.fontSize} ${style.fontFamily}`;const prepared=window.Pretext.prepare(input.value||'继续提问',font);const result=window.Pretext.layout(prepared,width,parseFloat(style.lineHeight));input.style.height=`${Math.max(44,Math.min(145,result.height+7))}px`;}else{input.style.height='44px';input.style.height=`${Math.min(145,Math.max(44,input.scrollHeight))}px`;}}
  window.addEventListener('resize',syncSidebarState);hydrateIcons();route();renderSelectedSkill();document.fonts.ready.then(resizeComposer);new ResizeObserver(resizeComposer).observe($('.composer'));$('#conversation').classList.add('initial-view');$('#conversation').addEventListener('animationend',()=>$('#conversation').classList.remove('initial-view'),{once:true});
})();
