-- analysis owns conditions and clarifications; immutable versions preserve old query attribution.
ALTER TABLE analysis_tasks ADD COLUMN lifecycle VARCHAR(16) NOT NULL DEFAULT 'active', ADD COLUMN phase VARCHAR(32) NOT NULL DEFAULT 'investigating';
CREATE TABLE condition_revisions(task_id VARCHAR(64) NOT NULL,version BIGINT UNSIGNED NOT NULL,body JSON NOT NULL,PRIMARY KEY(task_id,version));
CREATE TABLE clarifications(id VARCHAR(64) PRIMARY KEY,conversation_id VARCHAR(64) NOT NULL,task_id VARCHAR(64),condition_version BIGINT UNSIGNED,question TEXT NOT NULL,options JSON NOT NULL,state VARCHAR(16) NOT NULL DEFAULT 'open');
-- queries owns drafts, execution identity and platform references, never durable result rows.
CREATE TABLE query_requests(id VARCHAR(64) PRIMARY KEY,conversation_id VARCHAR(64) NOT NULL,owner_id VARCHAR(64) NOT NULL,task_id VARCHAR(64) NOT NULL,condition_version BIGINT UNSIGNED NOT NULL,draft_version BIGINT UNSIGNED NOT NULL,operation_id VARCHAR(64) NOT NULL UNIQUE,sql_text TEXT NOT NULL,parameters JSON NOT NULL,target_id VARCHAR(64) NOT NULL,target_version VARCHAR(64) NOT NULL,summary TEXT NOT NULL,knowledge_refs JSON NOT NULL,check_state VARCHAR(16) NOT NULL,confirmation_state VARCHAR(32) NOT NULL DEFAULT 'awaiting_confirmation',execution_state VARCHAR(32) NOT NULL DEFAULT 'not_submitted',cancel_state VARCHAR(32) NOT NULL DEFAULT 'none',confirmation_key VARCHAR(64),budget_scope_id VARCHAR(64) NOT NULL,result_ref VARCHAR(64),error_code VARCHAR(64),lease_owner VARCHAR(64),lease_until DATETIME(3),lease_epoch BIGINT UNSIGNED NOT NULL DEFAULT 0,result_notified BOOLEAN NOT NULL DEFAULT 0,created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),INDEX(conversation_id),INDEX(execution_state,lease_until));
-- ingestion owns source snapshots and heads; knowledge owns effective semantics and versions.
CREATE TABLE source_heads(id VARCHAR(64) PRIMARY KEY,space_id VARCHAR(64) NOT NULL,version BIGINT UNSIGNED NOT NULL,fingerprint VARCHAR(64) NOT NULL);
CREATE TABLE source_snapshots(source_id VARCHAR(64) NOT NULL,version BIGINT UNSIGNED NOT NULL,body LONGTEXT NOT NULL,complete BOOLEAN NOT NULL DEFAULT TRUE,PRIMARY KEY(source_id,version));
CREATE TABLE knowledge_objects(id VARCHAR(64) PRIMARY KEY,space_id VARCHAR(64) NOT NULL,kind VARCHAR(32) NOT NULL,name VARCHAR(512) NOT NULL,version BIGINT UNSIGNED NOT NULL,state VARCHAR(16) NOT NULL,body JSON NOT NULL,source_id VARCHAR(64),source_version BIGINT UNSIGNED NOT NULL,updated_by VARCHAR(64) NOT NULL,INDEX(space_id,state));
CREATE TABLE knowledge_versions(object_id VARCHAR(64) NOT NULL,version BIGINT UNSIGNED NOT NULL,body JSON NOT NULL,PRIMARY KEY(object_id,version));
CREATE TABLE knowledge_operations(owner_id VARCHAR(64) NOT NULL,operation_id VARCHAR(64) NOT NULL,fingerprint VARCHAR(64) NOT NULL,receipt JSON NOT NULL,PRIMARY KEY(owner_id,operation_id));
CREATE TABLE semantic_change_proposals(id VARCHAR(64) PRIMARY KEY,owner_id VARCHAR(64) NOT NULL,space_id VARCHAR(64) NOT NULL,body JSON NOT NULL,state VARCHAR(16) NOT NULL DEFAULT 'open');
-- assets owns private memory, Skill versions, user selections and adoption history.
CREATE TABLE personal_assets(id VARCHAR(64) PRIMARY KEY,owner_id VARCHAR(64) NOT NULL,space_id VARCHAR(64) NOT NULL,version BIGINT UNSIGNED NOT NULL,kind VARCHAR(16) NOT NULL,state VARCHAR(16) NOT NULL,body JSON NOT NULL,INDEX(owner_id,space_id,state));
CREATE TABLE personal_asset_versions(asset_id VARCHAR(64) NOT NULL,version BIGINT UNSIGNED NOT NULL,body JSON NOT NULL,PRIMARY KEY(asset_id,version));
CREATE TABLE asset_operations(owner_id VARCHAR(64) NOT NULL,operation_id VARCHAR(64) NOT NULL,fingerprint VARCHAR(64) NOT NULL,receipt JSON NOT NULL,PRIMARY KEY(owner_id,operation_id));
CREATE TABLE skill_selections(id VARCHAR(64) PRIMARY KEY,owner_id VARCHAR(64) NOT NULL,conversation_id VARCHAR(64) NOT NULL,asset_id VARCHAR(64) NOT NULL,asset_version BIGINT UNSIGNED NOT NULL,UNIQUE(owner_id,conversation_id,asset_id));
CREATE TABLE asset_adoptions(id VARCHAR(64) PRIMARY KEY,owner_id VARCHAR(64) NOT NULL,asset_id VARCHAR(64) NOT NULL,asset_version BIGINT UNSIGNED NOT NULL,run_id VARCHAR(64) NOT NULL,usage_kind VARCHAR(32) NOT NULL,UNIQUE(run_id,asset_id,asset_version));
ALTER TABLE conversations ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE conversation_messages ADD COLUMN routing_state VARCHAR(32) NOT NULL DEFAULT 'pending';
